#!/usr/bin/env node
/**
 * Staging bootstrap — creates fake accounts and representative data on a
 * SEPARATE Supabase staging project.
 *
 *   node supabase/staging/bootstrap.mjs            # dry run, writes nothing
 *   node supabase/staging/bootstrap.mjs --apply    # actually writes
 *
 * Server-side only. It needs the service-role key, which must never reach a
 * browser, a commit, or a chat window — supply it through
 * SUPABASE_STAGING_SERVICE_ROLE_KEY, ideally from a gitignored
 * `.env.staging.local` you source before running.
 *
 * Idempotent. See README.md ("Re-running") for exactly what a second run does.
 *
 * Order is forced by the schema: Auth users first (their ids are generated by
 * Auth), then `profiles`, then `organization_members` — `organization_members`
 * .user_id references `profiles.id`, so the reverse order fails on the foreign
 * key. Nothing here writes to `auth.users` directly; only the Auth Admin API
 * creates users.
 */
import { createClient } from '@supabase/supabase-js'
import {
  STAGING_IDS,
  STAGING_ORG_NAME,
  STORAGE_BUCKET,
  assertSupportedNode,
  buildStagingAccounts,
  buildStagingFixtures,
  readConfig,
  sampleImageBytes,
  stagingStorageObjectPath,
} from './plan.mjs'

const APPLY = process.argv.includes('--apply')

function log(...args) {
  console.log(...args)
}

function fail(message) {
  console.error(`\n✖ ${message}\n`)
  process.exit(1)
}

/** Walks every Auth user page and maps email -> user. */
async function listAllUsers(admin) {
  const byEmail = new Map()
  for (let page = 1; ; page += 1) {
    const { data, error } = await admin.auth.admin.listUsers({ page, perPage: 200 })
    if (error) throw error
    for (const user of data.users) {
      if (user.email) byEmail.set(user.email.toLowerCase(), user)
    }
    if (data.users.length < 200) break
  }
  return byEmail
}

async function main() {
  // Runtime check first: before configuration is read and before any
  // network call, so an unsupported Node fails with a version message
  // rather than a confusing WebSocket error from deep inside the client.
  try {
    assertSupportedNode()
  } catch (err) {
    fail(err.message)
  }

  let config
  try {
    config = readConfig(process.env)
  } catch (err) {
    fail(`${err.message}\n\n  See supabase/staging/.env.example for the full list.`)
  }

  const accounts = buildStagingAccounts(config.emailDomain)
  const fixtures = buildStagingFixtures()

  log('Sanad Inventory — staging bootstrap')
  log('───────────────────────────────────')
  log(`  target project ref : ${config.projectRef}`)
  log(`  organization       : ${STAGING_ORG_NAME} (${STAGING_IDS.organization})`)
  log(`  accounts           : ${accounts.map((a) => `${a.role}=${a.email}`).join(', ')}`)
  log(`  storage bucket     : ${STORAGE_BUCKET}`)
  log(`  mode               : ${APPLY ? 'APPLY (writes)' : 'DRY RUN (no writes)'}`)
  log('')

  if (!APPLY) {
    log('Dry run only. Nothing was written.')
    log('Re-run with --apply once the target above is correct.')
    return
  }

  const admin = createClient(config.url, config.serviceRoleKey, {
    auth: { autoRefreshToken: false, persistSession: false },
  })

  // ── 1. Auth users (Admin API only) ──────────────────────────────────
  log('1/6  Auth users')
  const existing = await listAllUsers(admin)
  const resolved = []

  for (const account of accounts) {
    const found = existing.get(account.email.toLowerCase())
    if (found) {
      // Re-runs reset the password and metadata so the documented credentials
      // always work, without creating a duplicate account.
      const { data, error } = await admin.auth.admin.updateUserById(found.id, {
        password: config.password,
        email_confirm: true,
        user_metadata: { full_name: account.fullName, staging: true, role_hint: account.role },
      })
      if (error) throw error
      resolved.push({ ...account, id: data.user.id, created: false })
      log(`     ~ ${account.email} (existing, updated)`)
    } else {
      const { data, error } = await admin.auth.admin.createUser({
        email: account.email,
        password: config.password,
        email_confirm: true,
        user_metadata: { full_name: account.fullName, staging: true, role_hint: account.role },
      })
      if (error) throw error
      resolved.push({ ...account, id: data.user.id, created: true })
      log(`     + ${account.email} (created)`)
    }
  }

  // ── 2. profiles — BEFORE memberships (FK) ───────────────────────────
  log('2/6  profiles')
  const { error: profileError } = await admin.from('profiles').upsert(
    resolved.map((a) => ({ id: a.id, full_name: a.fullName })),
    { onConflict: 'id' },
  )
  if (profileError) throw profileError
  log(`     ✓ ${resolved.length} rows`)

  // ── 3. organization ─────────────────────────────────────────────────
  log('3/6  organization')
  const { error: orgError } = await admin.from('organizations').upsert(
    [{ id: STAGING_IDS.organization, slug: config.orgSlug, name: STAGING_ORG_NAME }],
    { onConflict: 'id' },
  )
  if (orgError) throw orgError
  log(`     ✓ ${STAGING_ORG_NAME}`)

  // ── 4. memberships ──────────────────────────────────────────────────
  log('4/6  organization_members')
  const { error: memberError } = await admin.from('organization_members').upsert(
    resolved.map((a) => ({
      organization_id: STAGING_IDS.organization,
      user_id: a.id,
      role: a.role,
    })),
    { onConflict: 'organization_id,user_id' },
  )
  if (memberError) throw memberError
  log(`     ✓ ${resolved.map((a) => a.role).join(', ')}`)

  // ── 5. representative data ──────────────────────────────────────────
  log('5/6  inventory / scan / activity fixtures')
  for (const [table, rows] of Object.entries(fixtures)) {
    if (!rows.length) continue
    const { error } = await admin.from(table).upsert(rows, { onConflict: 'id' })
    if (error) throw error
    log(`     ✓ ${table} (${rows.length})`)
  }

  // ── 6. storage ──────────────────────────────────────────────────────
  log('6/6  storage')
  const { data: buckets, error: bucketListError } = await admin.storage.listBuckets()
  if (bucketListError) throw bucketListError
  if (!buckets.some((b) => b.id === STORAGE_BUCKET)) {
    const { error } = await admin.storage.createBucket(STORAGE_BUCKET, { public: false })
    if (error) throw error
    log(`     + bucket ${STORAGE_BUCKET} (private)`)
  } else {
    log(`     ~ bucket ${STORAGE_BUCKET} already exists`)
  }

  const objectPath = stagingStorageObjectPath()
  const { error: uploadError } = await admin.storage
    .from(STORAGE_BUCKET)
    .upload(objectPath, sampleImageBytes(), {
      contentType: 'image/png',
      upsert: true, // makes re-runs idempotent
    })
  if (uploadError) throw uploadError
  log(`     ✓ ${objectPath}`)

  log('')
  log('Done. Sign in at your staging frontend with any of:')
  for (const a of resolved) log(`   ${a.role.padEnd(6)}  ${a.email}`)
  log('')
  log('Password: the value of STAGING_USER_PASSWORD (not printed).')
}

main().catch((err) => {
  fail(err?.message ?? String(err))
})
